### ISSUE TITLE
arrests category

### ISSUE THREAD

**Issue by antiboredom** [frnsys/scanmap#4]
should there be an "arrests" category?

**Comment by frnsys** [comment]
that would be great--one other category that comes up is aviation

**Comment by nocturnalmusings** [comment]
Typically aviation calls are made for tracking requests and updates, but knowing where aviation is tracking is useful

**Comment by frnsys** [comment]
should I just change "prisoner_vans" to "arrests" ? or combine both somehow

**Comment by davidtorcivia** [comment]
Sometimes they call wagons, but don't seem to use them so they're not exactly the same.

**Comment by unitof** [comment]
Made a PR! #11

**Comment by beamalsky** [comment]
having separate `prisoner_van` and `arrest` categories would definitely be useful in Chicago

**Comment by frnsys** [comment]
added!
